// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OngProject.Infrastructure.Data;

namespace OngProject.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OngProject.Core.Models.ActivitiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content from activity 1",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 749, DateTimeKind.Local).AddTicks(6020),
                            Image = "ImageActivities1.jpg",
                            IsDeleted = false,
                            Name = "Activity 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content from activity 2",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7640),
                            Image = "ImageActivities2.jpg",
                            IsDeleted = false,
                            Name = "Activity 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content from activity 3",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7801),
                            Image = "ImageActivities3.jpg",
                            IsDeleted = false,
                            Name = "Activity 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content from activity 4",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7823),
                            Image = "ImageActivities4.jpg",
                            IsDeleted = false,
                            Name = "Activity 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content from activity 5",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7840),
                            Image = "ImageActivities5.jpg",
                            IsDeleted = false,
                            Name = "Activity 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content from activity 6",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7862),
                            Image = "ImageActivities6.jpg",
                            IsDeleted = false,
                            Name = "Activity 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Content from activity 7",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7878),
                            Image = "ImageActivities7.jpg",
                            IsDeleted = false,
                            Name = "Activity 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Content from activity 8",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7894),
                            Image = "ImageActivities8.jpg",
                            IsDeleted = false,
                            Name = "Activity 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Content from activity 9",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(7910),
                            Image = "ImageActivities9.jpg",
                            IsDeleted = false,
                            Name = "Activity 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Content from activity 10",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 751, DateTimeKind.Local).AddTicks(8019),
                            Image = "ImageActivities10.jpg",
                            IsDeleted = false,
                            Name = "Activity 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3401),
                            Description = "Descripcion 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories1.jpg",
                            IsDeleted = false,
                            Name = "name 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3603),
                            Description = "Descripcion 2Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories2.jpg",
                            IsDeleted = false,
                            Name = "name 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3632),
                            Description = "Descripcion 3Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories3.jpg",
                            IsDeleted = false,
                            Name = "name 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3650),
                            Description = "Descripcion 4Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories4.jpg",
                            IsDeleted = false,
                            Name = "name 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3729),
                            Description = "Descripcion 5Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories5.jpg",
                            IsDeleted = false,
                            Name = "name 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3754),
                            Description = "Descripcion 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories6.jpg",
                            IsDeleted = false,
                            Name = "name 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3772),
                            Description = "Descripcion 7Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories7.jpg",
                            IsDeleted = false,
                            Name = "name 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3788),
                            Description = "Descripcion 8Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories8.jpg",
                            IsDeleted = false,
                            Name = "name 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3805),
                            Description = "Descripcion 9Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories9.jpg",
                            IsDeleted = false,
                            Name = "name 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(3846),
                            Description = "Descripcion 10Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "imageCategories10.jpg",
                            IsDeleted = false,
                            Name = "name 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("post_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8599),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8790),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8814),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8832),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 5,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8849),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 6,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8867),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 7,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8883),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 8,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8899),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 9,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8914),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 10,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8932),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 11,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8947),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 12,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8963),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 13,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8979),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 14,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(8994),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 15,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9010),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 16,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9025),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 17,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9041),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 18,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9142),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 19,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9158),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 20,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9174),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 21,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9189),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 22,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9205),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 23,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9220),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 24,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9235),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 25,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9251),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 26,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9266),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 27,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9281),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 28,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9297),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        },
                        new
                        {
                            Id = 29,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9313),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        },
                        new
                        {
                            Id = 30,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(9328),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.ContactsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(596),
                            Email = "email1gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message1",
                            Name = "Contact 1",
                            Phone = 92841269
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(797),
                            Email = "email2gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message2",
                            Name = "Contact 2",
                            Phone = 58242469
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(822),
                            Email = "email3gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message3",
                            Name = "Contact 3",
                            Phone = 15189100
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(840),
                            Email = "email4gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message4",
                            Name = "Contact 4",
                            Phone = 94166877
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(940),
                            Email = "email5gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message5",
                            Name = "Contact 5",
                            Phone = 48057298
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(964),
                            Email = "email6gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message6",
                            Name = "Contact 6",
                            Phone = 71214118
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(981),
                            Email = "email7gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message7",
                            Name = "Contact 7",
                            Phone = 69637696
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(997),
                            Email = "email8gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message8",
                            Name = "Contact 8",
                            Phone = 82926231
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(1013),
                            Email = "email9gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message9",
                            Name = "Contact 9",
                            Phone = 35504059
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(1031),
                            Email = "email10gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message10",
                            Name = "Contact 10",
                            Phone = 27810326
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.MemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(8999),
                            Description = "Descripcion1Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member1",
                            Image = "imageMembers1.jpg",
                            InstagramUrl = "https://instagram/member1",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member1",
                            Name = "name1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9214),
                            Description = "Descripcion2Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member2",
                            Image = "imageMembers2.jpg",
                            InstagramUrl = "https://instagram/member2",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member2",
                            Name = "name2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9242),
                            Description = "Descripcion3Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member3",
                            Image = "imageMembers3.jpg",
                            InstagramUrl = "https://instagram/member3",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member3",
                            Name = "name3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9261),
                            Description = "Descripcion4Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member4",
                            Image = "imageMembers4.jpg",
                            InstagramUrl = "https://instagram/member4",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member4",
                            Name = "name4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9279),
                            Description = "Descripcion5Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member5",
                            Image = "imageMembers5.jpg",
                            InstagramUrl = "https://instagram/member5",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member5",
                            Name = "name5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9301),
                            Description = "Descripcion6Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member6",
                            Image = "imageMembers6.jpg",
                            InstagramUrl = "https://instagram/member6",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member6",
                            Name = "name6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9377),
                            Description = "Descripcion7Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member7",
                            Image = "imageMembers7.jpg",
                            InstagramUrl = "https://instagram/member7",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member7",
                            Name = "name7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9399),
                            Description = "Descripcion8Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member8",
                            Image = "imageMembers8.jpg",
                            InstagramUrl = "https://instagram/member8",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member8",
                            Name = "name8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9416),
                            Description = "Descripcion9Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member9",
                            Image = "imageMembers9.jpg",
                            InstagramUrl = "https://instagram/member9",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member9",
                            Name = "name9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(9436),
                            Description = "Descripcion10Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member10",
                            Image = "imageMembers10.jpg",
                            InstagramUrl = "https://instagram/member10",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member10",
                            Name = "name10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.NewsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Content 1 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(8870),
                            Image = "imageNews1.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Content 2 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9093),
                            Image = "imageNews2.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "Content 3 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9120),
                            Image = "imageNews3.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = "Content 4 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9195),
                            Image = "imageNews4.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Content = "Content 5 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9217),
                            Image = "imageNews5.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Content = "Content 6 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9238),
                            Image = "imageNews6.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Content = "Content 7 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9256),
                            Image = "imageNews7.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Content = "Content 8 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9273),
                            Image = "imageNews8.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Content = "Content 9 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9291),
                            Image = "imageNews9.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Content = "Content 10 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9311),
                            Image = "imageNews10.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9330),
                            Image = "imageNews11.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9348),
                            Image = "imageNews12.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9365),
                            Image = "imageNews14.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 760, DateTimeKind.Local).AddTicks(9451),
                            Image = "imageNews15.jpg",
                            IsDeleted = false,
                            Name = "new's name "
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.OrganizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutUsText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Adress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("WelcomeText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUsText = "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            Adress = "Catamarca 1585 , CP: 1585",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 761, DateTimeKind.Local).AddTicks(4386),
                            Email = "somomasong@gmail.com",
                            FacebookUrl = "https://facebook.com/organization",
                            Image = "imageOrganization.jpg",
                            IsDeleted = false,
                            Name = "Somos Más",
                            Phone = 1128559685,
                            WelcomeText = "Bienvenidos a nuestro sitio web"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 752, DateTimeKind.Local).AddTicks(2295),
                            Description = "Admin User",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 752, DateTimeKind.Local).AddTicks(2489),
                            Description = "Standard User",
                            IsDeleted = false,
                            Name = "Standard"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.SlideModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(4801),
                            ImageUrl = "imagenSlides1.jpg",
                            IsDeleted = false,
                            Order = 1,
                            OrganizationId = "1",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5000),
                            ImageUrl = "imagenSlides2.jpg",
                            IsDeleted = false,
                            Order = 2,
                            OrganizationId = "2",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5024),
                            ImageUrl = "imagenSlides3.jpg",
                            IsDeleted = false,
                            Order = 3,
                            OrganizationId = "3",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5042),
                            ImageUrl = "imagenSlides4.jpg",
                            IsDeleted = false,
                            Order = 4,
                            OrganizationId = "4",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5059),
                            ImageUrl = "imagenSlides5.jpg",
                            IsDeleted = false,
                            Order = 5,
                            OrganizationId = "5",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5079),
                            ImageUrl = "imagenSlides6.jpg",
                            IsDeleted = false,
                            Order = 6,
                            OrganizationId = "6",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5096),
                            ImageUrl = "imagenSlides7.jpg",
                            IsDeleted = false,
                            Order = 7,
                            OrganizationId = "7",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5111),
                            ImageUrl = "imagenSlides8.jpg",
                            IsDeleted = false,
                            Order = 8,
                            OrganizationId = "8",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5128),
                            ImageUrl = "imagenSlides9.jpg",
                            IsDeleted = false,
                            Order = 9,
                            OrganizationId = "9",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 758, DateTimeKind.Local).AddTicks(5244),
                            ImageUrl = "imagenSlides10.jpg",
                            IsDeleted = false,
                            Order = 10,
                            OrganizationId = "10",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.TestimonialsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(65535)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content1Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3407),
                            Image = "imageTestimonials1.jpg",
                            IsDeleted = false,
                            Name = "name 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content2Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3704),
                            Image = "imageTestimonials2.jpg",
                            IsDeleted = false,
                            Name = "name 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content3Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3735),
                            Image = "imageTestimonials3.jpg",
                            IsDeleted = false,
                            Name = "name 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content4Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3753),
                            Image = "imageTestimonials4.jpg",
                            IsDeleted = false,
                            Name = "name 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content5Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3769),
                            Image = "imageTestimonials5.jpg",
                            IsDeleted = false,
                            Name = "name 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content6Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3790),
                            Image = "imageTestimonials6.jpg",
                            IsDeleted = false,
                            Name = "name 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Content7Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3806),
                            Image = "imageTestimonials7.jpg",
                            IsDeleted = false,
                            Name = "name 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Content8Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3822),
                            Image = "imageTestimonials8.jpg",
                            IsDeleted = false,
                            Name = "name 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Content9Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3838),
                            Image = "imageTestimonials9.jpg",
                            IsDeleted = false,
                            Name = "name 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Content10Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 759, DateTimeKind.Local).AddTicks(3857),
                            Image = "imageTestimonials10.jpg",
                            IsDeleted = false,
                            Name = "name 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("roleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(2481),
                            IsDeleted = false,
                            email = "mail1@Mail.com",
                            firstName = "User 1",
                            lastName = "AdminUser 1",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers1.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3372),
                            IsDeleted = false,
                            email = "mail2@Mail.com",
                            firstName = "User 2",
                            lastName = "AdminUser 2",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers2.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3596),
                            IsDeleted = false,
                            email = "mail3@Mail.com",
                            firstName = "User 3",
                            lastName = "AdminUser 3",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers3.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3656),
                            IsDeleted = false,
                            email = "mail4@Mail.com",
                            firstName = "User 4",
                            lastName = "AdminUser 4",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers4.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3706),
                            IsDeleted = false,
                            email = "mail5@Mail.com",
                            firstName = "User 5",
                            lastName = "AdminUser 5",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers5.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3870),
                            IsDeleted = false,
                            email = "mail6@Mail.com",
                            firstName = "User 6",
                            lastName = "AdminUser 6",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers6.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3931),
                            IsDeleted = false,
                            email = "mail7@Mail.com",
                            firstName = "User 7",
                            lastName = "AdminUser 7",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers7.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(3980),
                            IsDeleted = false,
                            email = "mail8@Mail.com",
                            firstName = "User 8",
                            lastName = "AdminUser 8",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers8.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4083),
                            IsDeleted = false,
                            email = "mail9@Mail.com",
                            firstName = "User 9",
                            lastName = "AdminUser 9",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers9.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4142),
                            IsDeleted = false,
                            email = "mail10@Mail.com",
                            firstName = "User 10",
                            lastName = "AdminUser 10",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "TestUsers10.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4196),
                            IsDeleted = false,
                            email = "mail11@Mail.com",
                            firstName = "User 11",
                            lastName = "RegularUser 11",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers11.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4297),
                            IsDeleted = false,
                            email = "mail12@Mail.com",
                            firstName = "User 12",
                            lastName = "RegularUser 12",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers12.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4353),
                            IsDeleted = false,
                            email = "mail13@Mail.com",
                            firstName = "User 13",
                            lastName = "RegularUser 13",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers13.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4402),
                            IsDeleted = false,
                            email = "mail14@Mail.com",
                            firstName = "User 14",
                            lastName = "RegularUser 14",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers14.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4450),
                            IsDeleted = false,
                            email = "mail15@Mail.com",
                            firstName = "User 15",
                            lastName = "RegularUser 15",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers15.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4577),
                            IsDeleted = false,
                            email = "mail16@Mail.com",
                            firstName = "User 16",
                            lastName = "RegularUser 16",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers16.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4630),
                            IsDeleted = false,
                            email = "mail17@Mail.com",
                            firstName = "User 17",
                            lastName = "RegularUser 17",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers17.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4681),
                            IsDeleted = false,
                            email = "mail18@Mail.com",
                            firstName = "User 18",
                            lastName = "RegularUser 18",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers18.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4780),
                            IsDeleted = false,
                            email = "mail19@Mail.com",
                            firstName = "User 19",
                            lastName = "RegularUser 19",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers19.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 8, 11, 20, 34, 42, 757, DateTimeKind.Local).AddTicks(4833),
                            IsDeleted = false,
                            email = "mail20@Mail.com",
                            firstName = "User 20",
                            lastName = "RegularUser 20",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "TestUsers20.jpg",
                            roleId = 2
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.NewsModel", b =>
                {
                    b.HasOne("OngProject.Core.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OngProject.Core.Models.UserModel", b =>
                {
                    b.HasOne("OngProject.Core.Models.RoleModel", "RoleModel")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
