// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OngProject.Infrastructure.Data;

namespace OngProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OngProject.Core.Models.ActivitiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content from activity 1",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 78, DateTimeKind.Local).AddTicks(5734),
                            Image = "Image from activity 1",
                            IsDeleted = false,
                            Name = "Activity 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content from activity 2",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7267),
                            Image = "Image from activity 2",
                            IsDeleted = false,
                            Name = "Activity 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content from activity 3",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7449),
                            Image = "Image from activity 3",
                            IsDeleted = false,
                            Name = "Activity 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content from activity 4",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7475),
                            Image = "Image from activity 4",
                            IsDeleted = false,
                            Name = "Activity 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content from activity 5",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7498),
                            Image = "Image from activity 5",
                            IsDeleted = false,
                            Name = "Activity 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content from activity 6",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7528),
                            Image = "Image from activity 6",
                            IsDeleted = false,
                            Name = "Activity 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Content from activity 7",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7548),
                            Image = "Image from activity 7",
                            IsDeleted = false,
                            Name = "Activity 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Content from activity 8",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7568),
                            Image = "Image from activity 8",
                            IsDeleted = false,
                            Name = "Activity 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Content from activity 9",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7588),
                            Image = "Image from activity 9",
                            IsDeleted = false,
                            Name = "Activity 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Content from activity 10",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 84, DateTimeKind.Local).AddTicks(7611),
                            Image = "Image from activity 10",
                            IsDeleted = false,
                            Name = "Activity 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(6738),
                            Description = "Descripcion 1Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 1",
                            IsDeleted = false,
                            Name = "name 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7151),
                            Description = "Descripcion 2Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 2",
                            IsDeleted = false,
                            Name = "name 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7353),
                            Description = "Descripcion 3Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 3",
                            IsDeleted = false,
                            Name = "name 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7417),
                            Description = "Descripcion 4Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 4",
                            IsDeleted = false,
                            Name = "name 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7450),
                            Description = "Descripcion 5Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 5",
                            IsDeleted = false,
                            Name = "name 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7509),
                            Description = "Descripcion 6Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 6",
                            IsDeleted = false,
                            Name = "name 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7591),
                            Description = "Descripcion 7Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 7",
                            IsDeleted = false,
                            Name = "name 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7661),
                            Description = "Descripcion 8Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 8",
                            IsDeleted = false,
                            Name = "name 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7695),
                            Description = "Descripcion 9Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 9",
                            IsDeleted = false,
                            Name = "name 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 103, DateTimeKind.Local).AddTicks(7772),
                            Description = "Descripcion 10Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
                            Image = "image 10",
                            IsDeleted = false,
                            Name = "name 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("post_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1463),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1714),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "body of post_id=1",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1745),
                            IsDeleted = false,
                            User_id = 1,
                            post_id = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1768),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 5,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1789),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 6,
                            Body = "body of post_id=2",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1813),
                            IsDeleted = false,
                            User_id = 2,
                            post_id = 2
                        },
                        new
                        {
                            Id = 7,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1833),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 8,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1854),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 9,
                            Body = "body of post_id=3",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1874),
                            IsDeleted = false,
                            User_id = 3,
                            post_id = 3
                        },
                        new
                        {
                            Id = 10,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1896),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 11,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(1916),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 12,
                            Body = "body of post_id=4",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2240),
                            IsDeleted = false,
                            User_id = 4,
                            post_id = 4
                        },
                        new
                        {
                            Id = 13,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2272),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 14,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2292),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 15,
                            Body = "body of post_id=5",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2312),
                            IsDeleted = false,
                            User_id = 5,
                            post_id = 5
                        },
                        new
                        {
                            Id = 16,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2333),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 17,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2353),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 18,
                            Body = "body of post_id=6",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2377),
                            IsDeleted = false,
                            User_id = 6,
                            post_id = 6
                        },
                        new
                        {
                            Id = 19,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2398),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 20,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2418),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 21,
                            Body = "body of post_id=7",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2439),
                            IsDeleted = false,
                            User_id = 7,
                            post_id = 7
                        },
                        new
                        {
                            Id = 22,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2459),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 23,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2479),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 24,
                            Body = "body of post_id=8",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2500),
                            IsDeleted = false,
                            User_id = 8,
                            post_id = 8
                        },
                        new
                        {
                            Id = 25,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2521),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 26,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2541),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 27,
                            Body = "body of post_id=9",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2562),
                            IsDeleted = false,
                            User_id = 9,
                            post_id = 9
                        },
                        new
                        {
                            Id = 28,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2584),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        },
                        new
                        {
                            Id = 29,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2604),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        },
                        new
                        {
                            Id = 30,
                            Body = "body of post_id=10",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(2624),
                            IsDeleted = false,
                            User_id = 10,
                            post_id = 10
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.ContactsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(1683),
                            Email = "email1gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message1",
                            Name = "Contact 1",
                            Phone = 27843668
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(1989),
                            Email = "email2gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message2",
                            Name = "Contact 2",
                            Phone = 14217134
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2071),
                            Email = "email3gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message3",
                            Name = "Contact 3",
                            Phone = 24096475
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2094),
                            Email = "email4gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message4",
                            Name = "Contact 4",
                            Phone = 51075563
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2115),
                            Email = "email5gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message5",
                            Name = "Contact 5",
                            Phone = 78199484
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2142),
                            Email = "email6gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message6",
                            Name = "Contact 6",
                            Phone = 25783295
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2162),
                            Email = "email7gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message7",
                            Name = "Contact 7",
                            Phone = 32762388
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2183),
                            Email = "email8gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message8",
                            Name = "Contact 8",
                            Phone = 32675654
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2202),
                            Email = "email9gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message9",
                            Name = "Contact 9",
                            Phone = 14536519
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(2226),
                            Email = "email10gmail.com",
                            IsDeleted = false,
                            Message = "Message Message Message Message10",
                            Name = "Contact 10",
                            Phone = 87717780
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.MemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(8076),
                            Description = "Descripcion1Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member1",
                            Image = "image 1",
                            InstagramUrl = "https://instagram/member1",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member1",
                            Name = "name1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(8830),
                            Description = "Descripcion2Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member2",
                            Image = "image 2",
                            InstagramUrl = "https://instagram/member2",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member2",
                            Name = "name2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(8890),
                            Description = "Descripcion3Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member3",
                            Image = "image 3",
                            InstagramUrl = "https://instagram/member3",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member3",
                            Name = "name3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(8929),
                            Description = "Descripcion4Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member4",
                            Image = "image 4",
                            InstagramUrl = "https://instagram/member4",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member4",
                            Name = "name4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(8964),
                            Description = "Descripcion5Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member5",
                            Image = "image 5",
                            InstagramUrl = "https://instagram/member5",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member5",
                            Name = "name5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(9113),
                            Description = "Descripcion6Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member6",
                            Image = "image 6",
                            InstagramUrl = "https://instagram/member6",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member6",
                            Name = "name6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(9161),
                            Description = "Descripcion7Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member7",
                            Image = "image 7",
                            InstagramUrl = "https://instagram/member7",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member7",
                            Name = "name7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(9198),
                            Description = "Descripcion8Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member8",
                            Image = "image 8",
                            InstagramUrl = "https://instagram/member8",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member8",
                            Name = "name8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(9232),
                            Description = "Descripcion9Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member9",
                            Image = "image 9",
                            InstagramUrl = "https://instagram/member9",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member9",
                            Name = "name9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 102, DateTimeKind.Local).AddTicks(9272),
                            Description = "Descripcion10Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            FacebookUrl = "https://facebook.com/member10",
                            Image = "image 10",
                            InstagramUrl = "https://instagram/member10",
                            IsDeleted = false,
                            LinkedinUrl = "https://Linkedin/member10",
                            Name = "name10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.NewsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Content 1 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(4465),
                            Image = "image 1",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Content 2 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(4904),
                            Image = "image 2",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "Content 3 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(4941),
                            Image = "image 3",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = "Content 4 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(4965),
                            Image = "image 4",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Content = "Content 5 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(4988),
                            Image = "image 5",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Content = "Content 6 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5014),
                            Image = "image 6",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Content = "Content 7 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5037),
                            Image = "image 7",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Content = "Content 8 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5059),
                            Image = "image 8",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Content = "Content 9 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5081),
                            Image = "image 9",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Content = "Content 10 Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5106),
                            Image = "image 10",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5128),
                            Image = "image ",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5209),
                            Image = "image ",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5231),
                            Image = "image ",
                            IsDeleted = false,
                            Name = "new's name "
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 104, DateTimeKind.Local).AddTicks(5250),
                            Image = "image ",
                            IsDeleted = false,
                            Name = "new's name "
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.OrganizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutUsText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Adress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("WelcomeText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUsText = "text about us1",
                            Adress = "Adress 111",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(2684),
                            Email = "email1@gmail.com",
                            FacebookUrl = "https://facebook.com/organization1",
                            Image = "image1",
                            IsDeleted = false,
                            Name = "organizacion1",
                            Phone = 84546122,
                            WelcomeText = "texto welcome to visit1"
                        },
                        new
                        {
                            Id = 2,
                            AboutUsText = "text about us2",
                            Adress = "Adress 222",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(2935),
                            Email = "email2@gmail.com",
                            FacebookUrl = "https://facebook.com/organization2",
                            Image = "image2",
                            IsDeleted = false,
                            Name = "organizacion2",
                            Phone = 98644092,
                            WelcomeText = "texto welcome to visit2"
                        },
                        new
                        {
                            Id = 3,
                            AboutUsText = "text about us3",
                            Adress = "Adress 333",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(2969),
                            Email = "email3@gmail.com",
                            FacebookUrl = "https://facebook.com/organization3",
                            Image = "image3",
                            IsDeleted = false,
                            Name = "organizacion3",
                            Phone = 57050465,
                            WelcomeText = "texto welcome to visit3"
                        },
                        new
                        {
                            Id = 4,
                            AboutUsText = "text about us4",
                            Adress = "Adress 444",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(2994),
                            Email = "email4@gmail.com",
                            FacebookUrl = "https://facebook.com/organization4",
                            Image = "image4",
                            IsDeleted = false,
                            Name = "organizacion4",
                            Phone = 29950874,
                            WelcomeText = "texto welcome to visit4"
                        },
                        new
                        {
                            Id = 5,
                            AboutUsText = "text about us5",
                            Adress = "Adress 555",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3019),
                            Email = "email5@gmail.com",
                            FacebookUrl = "https://facebook.com/organization5",
                            Image = "image5",
                            IsDeleted = false,
                            Name = "organizacion5",
                            Phone = 89660613,
                            WelcomeText = "texto welcome to visit5"
                        },
                        new
                        {
                            Id = 6,
                            AboutUsText = "text about us6",
                            Adress = "Adress 666",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3047),
                            Email = "email6@gmail.com",
                            FacebookUrl = "https://facebook.com/organization6",
                            Image = "image6",
                            IsDeleted = false,
                            Name = "organizacion6",
                            Phone = 46941046,
                            WelcomeText = "texto welcome to visit6"
                        },
                        new
                        {
                            Id = 7,
                            AboutUsText = "text about us7",
                            Adress = "Adress 777",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3072),
                            Email = "email7@gmail.com",
                            FacebookUrl = "https://facebook.com/organization7",
                            Image = "image7",
                            IsDeleted = false,
                            Name = "organizacion7",
                            Phone = 49801704,
                            WelcomeText = "texto welcome to visit7"
                        },
                        new
                        {
                            Id = 8,
                            AboutUsText = "text about us8",
                            Adress = "Adress 888",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3271),
                            Email = "email8@gmail.com",
                            FacebookUrl = "https://facebook.com/organization8",
                            Image = "image8",
                            IsDeleted = false,
                            Name = "organizacion8",
                            Phone = 25090800,
                            WelcomeText = "texto welcome to visit8"
                        },
                        new
                        {
                            Id = 9,
                            AboutUsText = "text about us9",
                            Adress = "Adress 999",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3306),
                            Email = "email9@gmail.com",
                            FacebookUrl = "https://facebook.com/organization9",
                            Image = "image9",
                            IsDeleted = false,
                            Name = "organizacion9",
                            Phone = 75096814,
                            WelcomeText = "texto welcome to visit9"
                        },
                        new
                        {
                            Id = 10,
                            AboutUsText = "text about us10",
                            Adress = "Adress 101010",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 105, DateTimeKind.Local).AddTicks(3333),
                            Email = "email10@gmail.com",
                            FacebookUrl = "https://facebook.com/organization10",
                            Image = "image10",
                            IsDeleted = false,
                            Name = "organizacion10",
                            Phone = 77616420,
                            WelcomeText = "texto welcome to visit10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 85, DateTimeKind.Local).AddTicks(2752),
                            Description = "Admin User",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 85, DateTimeKind.Local).AddTicks(3014),
                            Description = "Standard User",
                            IsDeleted = false,
                            Name = "Standard"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.SlideModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(6613),
                            ImageUrl = "imagen 1",
                            IsDeleted = false,
                            Order = 1,
                            OrganizationId = "1",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(6860),
                            ImageUrl = "imagen 2",
                            IsDeleted = false,
                            Order = 2,
                            OrganizationId = "2",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(6891),
                            ImageUrl = "imagen 3",
                            IsDeleted = false,
                            Order = 3,
                            OrganizationId = "3",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(6911),
                            ImageUrl = "imagen 4",
                            IsDeleted = false,
                            Order = 4,
                            OrganizationId = "4",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7098),
                            ImageUrl = "imagen 5",
                            IsDeleted = false,
                            Order = 5,
                            OrganizationId = "5",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7122),
                            ImageUrl = "imagen 6",
                            IsDeleted = false,
                            Order = 6,
                            OrganizationId = "6",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7142),
                            ImageUrl = "imagen 7",
                            IsDeleted = false,
                            Order = 7,
                            OrganizationId = "7",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7161),
                            ImageUrl = "imagen 8",
                            IsDeleted = false,
                            Order = 8,
                            OrganizationId = "8",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7180),
                            ImageUrl = "imagen 9",
                            IsDeleted = false,
                            Order = 9,
                            OrganizationId = "9",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 100, DateTimeKind.Local).AddTicks(7202),
                            ImageUrl = "imagen 10",
                            IsDeleted = false,
                            Order = 10,
                            OrganizationId = "10",
                            Text = "sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.TestimonialsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(65535)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content1Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7192),
                            Image = "image1",
                            IsDeleted = false,
                            Name = "name 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content2Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7439),
                            Image = "image2",
                            IsDeleted = false,
                            Name = "name 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content3Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7469),
                            Image = "image3",
                            IsDeleted = false,
                            Name = "name 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content4Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7491),
                            Image = "image4",
                            IsDeleted = false,
                            Name = "name 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content5Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7512),
                            Image = "image5",
                            IsDeleted = false,
                            Name = "name 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content6Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7536),
                            Image = "image6",
                            IsDeleted = false,
                            Name = "name 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Content7Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7559),
                            Image = "image7",
                            IsDeleted = false,
                            Name = "name 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Content8Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7580),
                            Image = "image8",
                            IsDeleted = false,
                            Name = "name 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Content9Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7702),
                            Image = "image9",
                            IsDeleted = false,
                            Name = "name 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Content10Lorem ipsum dolor sit amet,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 101, DateTimeKind.Local).AddTicks(7730),
                            Image = "image10",
                            IsDeleted = false,
                            Name = "name 10"
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("photo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("roleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(7488),
                            IsDeleted = false,
                            email = "mail1@Mail.com",
                            firstName = "User 1",
                            lastName = "AdminUser 1",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8480),
                            IsDeleted = false,
                            email = "mail2@Mail.com",
                            firstName = "User 2",
                            lastName = "AdminUser 2",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8698),
                            IsDeleted = false,
                            email = "mail3@Mail.com",
                            firstName = "User 3",
                            lastName = "AdminUser 3",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8774),
                            IsDeleted = false,
                            email = "mail4@Mail.com",
                            firstName = "User 4",
                            lastName = "AdminUser 4",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8839),
                            IsDeleted = false,
                            email = "mail5@Mail.com",
                            firstName = "User 5",
                            lastName = "AdminUser 5",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8920),
                            IsDeleted = false,
                            email = "mail6@Mail.com",
                            firstName = "User 6",
                            lastName = "AdminUser 6",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(8985),
                            IsDeleted = false,
                            email = "mail7@Mail.com",
                            firstName = "User 7",
                            lastName = "AdminUser 7",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9211),
                            IsDeleted = false,
                            email = "mail8@Mail.com",
                            firstName = "User 8",
                            lastName = "AdminUser 8",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9282),
                            IsDeleted = false,
                            email = "mail9@Mail.com",
                            firstName = "User 9",
                            lastName = "AdminUser 9",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9350),
                            IsDeleted = false,
                            email = "mail10@Mail.com",
                            firstName = "User 10",
                            lastName = "AdminUser 10",
                            password = "3b612c75a7b5048a435fb6ec81e52ff92d6d795a8b5a9c17070f6a63c97a53b2",
                            photo = "Test.jpg",
                            roleId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9487),
                            IsDeleted = false,
                            email = "mail11@Mail.com",
                            firstName = "User 11",
                            lastName = "RegularUser 11",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9557),
                            IsDeleted = false,
                            email = "mail12@Mail.com",
                            firstName = "User 12",
                            lastName = "RegularUser 12",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9620),
                            IsDeleted = false,
                            email = "mail13@Mail.com",
                            firstName = "User 13",
                            lastName = "RegularUser 13",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9744),
                            IsDeleted = false,
                            email = "mail14@Mail.com",
                            firstName = "User 14",
                            lastName = "RegularUser 14",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9811),
                            IsDeleted = false,
                            email = "mail15@Mail.com",
                            firstName = "User 15",
                            lastName = "RegularUser 15",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9873),
                            IsDeleted = false,
                            email = "mail16@Mail.com",
                            firstName = "User 16",
                            lastName = "RegularUser 16",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 98, DateTimeKind.Local).AddTicks(9933),
                            IsDeleted = false,
                            email = "mail17@Mail.com",
                            firstName = "User 17",
                            lastName = "RegularUser 17",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 99, DateTimeKind.Local).AddTicks(62),
                            IsDeleted = false,
                            email = "mail18@Mail.com",
                            firstName = "User 18",
                            lastName = "RegularUser 18",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 99, DateTimeKind.Local).AddTicks(128),
                            IsDeleted = false,
                            email = "mail19@Mail.com",
                            firstName = "User 19",
                            lastName = "RegularUser 19",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 8, 9, 10, 48, 8, 99, DateTimeKind.Local).AddTicks(189),
                            IsDeleted = false,
                            email = "mail20@Mail.com",
                            firstName = "User 20",
                            lastName = "RegularUser 20",
                            password = "a61a8adf60038792a2cb88e670b20540a9d6c2ca204ab754fc768950e79e7d36",
                            photo = "Test.jpg",
                            roleId = 2
                        });
                });

            modelBuilder.Entity("OngProject.Core.Models.NewsModel", b =>
                {
                    b.HasOne("OngProject.Core.Models.CategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OngProject.Core.Models.UserModel", b =>
                {
                    b.HasOne("OngProject.Core.Models.RoleModel", "RoleModel")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
